In [2]:
import tensorflow as tf
import numpy as np
tf.__version__

# https://www.tensorflow.org/tutorials/customization/basics?hl=ko

'2.0.0'

In [7]:
# 상수 : tf.constant()
s = tf.constant('Hello Tensorflow!!')
print(s)

a = tf.constant([[1.,2.],
                 [3.,4.]])
b = tf.constant([[1.,1.],
                 [0.,1.]])
c = tf.matmul(a,b)    # 내접 곱셈
print(c)

tf.Tensor(b'Hello Tensorflow!!', shape=(), dtype=string)
tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [9]:
# 변수 : tf.Variable()
# 초기값이 설정, 주로 텐서플로 내부에서 연산 시 변경되는 변수에 사용, 
# weight과 bias 
a = tf.Variable(100)
b = tf.Variable(200)
c = tf.add(a,b)
print(c)

tf.Tensor(300, shape=(), dtype=int32)


### tf.Tensor: 텐서 객체
#### 텐서는 다차원 배열로 넘파이(NumPy) ndarray 객체와 비슷하며,
#### tf.Tensor 객체는 데이터 타입과 크기를 가지고 있다.
#### 또한 tf.Tensor는 GPU 같은 가속기 메모리에 상주할 수 있다.
#### 텐서플로는 텐서를 생성하고 이용하는 풍부한 연산 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등.)를 제공하며
#### 연산수행 시 자동으로 텐서를 파이썬 네이티브(native) 타입으로 변환하여 연산한다


In [13]:
# 연산자
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [21]:
# 속성과 타입 변환
a = tf.constant([[1.,2.],
                 [3.,4.]])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)

# Tensor 객체를 ndarray로 변환
n = a.numpy()
print(n,type(n)) # <class 'numpy.ndarray'>

# 파이썬 native 타입으로 변환
a = tf.constant(10)
b = int(a)
print(b,type(b))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
10 <class 'int'>
