# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

#### https://greeksharifa.github.io/keras/2018/06/29/Keras-Tutorial/

### [1] Dense Layer

In [1]:
# keras_basic
import tensorflow as tf
import numpy as np

In [2]:
# keras 를 이용한 XOR 네트워크

# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]   # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]     # (4,1)

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
# Dense Layer 구현
model = tf.keras.Sequential([
    #  (4,2) * (2,2) = (4,2)
    # unites : 뉴런의 갯수
    # Param : 6 (W:4, b:2), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수: (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 2 = 6
    tf.keras.layers.Dense(units=2,activation='sigmoid',input_shape=(2,)),
    
    #  (4,2) * (2,1) = (4,1)
    # Param : 3 (W:2, b:1), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수:  (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 1 = 3
    tf.keras.layers.Dense(units=1,activation='sigmoid')                            
])

model.compile(optimizer = tf.keras.optimizers.Adam(lr=0.1),loss='mse',metrics=['accuracy'])
model.summary()  # 각 layer의 정보를 출력

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(x_train,y_train,epochs=1000,batch_size=1,verbose=1) # verbose=1, 메세지를 출력

Train on 4 samples
Epoch 1/1000
4/4 [==============================] - 1s 144ms/sample - loss: 0.3402 - accuracy: 0.5000
Epoch 2/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2798 - accuracy: 0.5000
Epoch 3/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2661 - accuracy: 0.5000
Epoch 4/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.2481 - accuracy: 0.2500
Epoch 5/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2540 - accuracy: 0.5000
Epoch 6/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2507 - accuracy: 0.5000
Epoch 7/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2522 - accuracy: 0.5000
Epoch 8/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2518 - accuracy: 0.5000
Epoch 9/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2542 - accuracy: 0.7500
Epoch 10/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.

Epoch 82/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0493 - accuracy: 1.0000
Epoch 83/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0441 - accuracy: 1.0000
Epoch 84/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0416 - accuracy: 1.0000
Epoch 85/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0399 - accuracy: 1.0000
Epoch 86/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0367 - accuracy: 1.0000
Epoch 87/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0344 - accuracy: 1.0000
Epoch 88/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0329 - accuracy: 1.0000
Epoch 89/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0308 - accuracy: 1.0000
Epoch 90/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0295 - accuracy: 1.0000
Epoch 91/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0281 - accurac

4/4 [==============================] - 0s 1ms/sample - loss: 0.0018 - accuracy: 1.0000
Epoch 243/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0018 - accuracy: 1.0000
Epoch 244/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.0018 - accuracy: 1.0000
Epoch 245/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0018 - accuracy: 1.0000
Epoch 246/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0018 - accuracy: 1.0000
Epoch 247/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0017 - accuracy: 1.0000
Epoch 248/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0017 - accuracy: 1.0000
Epoch 249/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0017 - accuracy: 1.0000
Epoch 250/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0017 - accuracy: 1.0000
Epoch 251/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0017 - accuracy: 

4/4 [==============================] - 0s 1ms/sample - loss: 6.6195e-04 - accuracy: 1.0000
Epoch 400/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.5889e-04 - accuracy: 1.0000
Epoch 401/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.5558e-04 - accuracy: 1.0000
Epoch 402/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.5288e-04 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 2ms/sample - loss: 6.4939e-04 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.4568e-04 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 998us/sample - loss: 6.4253e-04 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.4012e-04 - accuracy: 1.0000
Epoch 407/1000
4/4 [==============================] - 0s 1ms/sample - loss: 6.3695e-04 - accuracy: 1.0000
Epoch 408/1000
4/4 [==============================] - 0s 1m

4/4 [==============================] - 0s 1ms/sample - loss: 3.4148e-04 - accuracy: 1.0000
Epoch 553/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3995e-04 - accuracy: 1.0000
Epoch 554/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3853e-04 - accuracy: 1.0000
Epoch 555/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3745e-04 - accuracy: 1.0000
Epoch 556/1000
4/4 [==============================] - 0s 998us/sample - loss: 3.3623e-04 - accuracy: 1.0000
Epoch 557/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3473e-04 - accuracy: 1.0000
Epoch 558/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3376e-04 - accuracy: 1.0000
Epoch 559/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3251e-04 - accuracy: 1.0000
Epoch 560/1000
4/4 [==============================] - 0s 1ms/sample - loss: 3.3120e-04 - accuracy: 1.0000
Epoch 561/1000
4/4 [==============================] - 0s 1m

Epoch 706/1000
4/4 [==============================] - 0s 1ms/sample - loss: 2.0098e-04 - accuracy: 1.0000
Epoch 707/1000
4/4 [==============================] - 0s 2ms/sample - loss: 2.0030e-04 - accuracy: 1.0000
Epoch 708/1000
4/4 [==============================] - 0s 2ms/sample - loss: 1.9960e-04 - accuracy: 1.0000
Epoch 709/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.9908e-04 - accuracy: 1.0000
Epoch 710/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.9841e-04 - accuracy: 1.0000
Epoch 711/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.9781e-04 - accuracy: 1.0000
Epoch 712/1000
4/4 [==============================] - 0s 2ms/sample - loss: 1.9712e-04 - accuracy: 1.0000
Epoch 713/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.9654e-04 - accuracy: 1.0000
Epoch 714/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.9582e-04 - accuracy: 1.0000
Epoch 715/1000
4/4 [==========================

4/4 [==============================] - 0s 2ms/sample - loss: 1.2784e-04 - accuracy: 1.0000
Epoch 860/1000
4/4 [==============================] - 0s 2ms/sample - loss: 1.2744e-04 - accuracy: 1.0000
Epoch 861/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2712e-04 - accuracy: 1.0000
Epoch 862/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2681e-04 - accuracy: 1.0000
Epoch 863/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2645e-04 - accuracy: 1.0000
Epoch 864/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2605e-04 - accuracy: 1.0000
Epoch 865/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2574e-04 - accuracy: 1.0000
Epoch 866/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.2545e-04 - accuracy: 1.0000
Epoch 867/1000
4/4 [==============================] - 0s 997us/sample - loss: 1.2504e-04 - accuracy: 1.0000
Epoch 868/1000
4/4 [==============================] - 0s 1m

Epoch 936/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0371e-04 - accuracy: 1.0000
Epoch 937/1000
4/4 [==============================] - 0s 3ms/sample - loss: 1.0343e-04 - accuracy: 1.0000
Epoch 938/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0318e-04 - accuracy: 1.0000
Epoch 939/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0285e-04 - accuracy: 1.0000
Epoch 940/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0266e-04 - accuracy: 1.0000
Epoch 941/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0236e-04 - accuracy: 1.0000
Epoch 942/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0208e-04 - accuracy: 1.0000
Epoch 943/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0180e-04 - accuracy: 1.0000
Epoch 944/1000
4/4 [==============================] - 0s 1ms/sample - loss: 1.0152e-04 - accuracy: 1.0000
Epoch 945/1000
4/4 [==========================

In [5]:
preds = model.predict(x_train)
np.round(preds)

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [6]:
model.evaluate(x_train,y_train)  # [0.00010335762635804713, 1.0]

4/1 [========================================================================================================================] - 0s 15ms/sample - loss: 8.7579e-05 - accuracy: 1.0000


[8.757891919231042e-05, 1.0]

In [7]:
# X,Y input data 
x_train = np.array([[1.0,   2.0,  3.0,  4.0,  5.0],
                    [6.0,   7.0,  8.0,  9.0, 10.0],
                    [11.0, 12.0, 13.0, 14.0, 15.0]])  # (3,5)
                    
                    
y_train = np.array([[1.1,   2.2,  3.3,  4.4,  5.5],
                    [6.1,   7.2,  8.3,  9.4, 10.5],
                    [11.1, 12.2, 13.3, 14.4, 15.5]]) # (3,5)

model = tf.keras.Sequential([
    # (3,1) * (1,100) = (3,100)   , Param :200 (W:1*100, b:100), (1 + 1) * 100 = 200
    # tf.keras.layers.Dense(units=100, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 

    # (3,5) * (5,100) = (3,100)   , Param :600 (W:5*100, b:100), (5 + 1) * (100) = 600
    tf.keras.layers.Dense(units=100, activation='relu', input_shape=(5,)), # input data의 shape을 (?,5) 

    
    # (3,100) * (100,50) = (3,50)   , Param : 5050 (W:100*50, b:50), (100+1)*50 = 5050
    tf.keras.layers.Dense(units=50, activation='relu' ), 
    
    # (3,50) * (50,25) = (3,25)   , Param : 1275 (W:50*25, b:25), (50 + 1)* 25 = 1275
    tf.keras.layers.Dense(units=25, activation='relu' ),
    
    # (3,25) * (25,5) = (3,5)   , Param : 130 (W:25*5, b:5), (25 + 1) * 5 = 130
    tf.keras.layers.Dense(units=5 , activation='relu' ),
    
#     # (3,5) * (5,1) = (3,1)   , Pram : 6  (W:5*1, b:1), (5 + 1) *1 = 6
#     tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 100)               600       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 130       
Total params: 7,055
Trainable params: 7,055
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x_train, y_train, epochs=100)

Train on 3 samples
Epoch 1/100
3/3 [==============================] - 0s 106ms/sample - loss: 72.9812
Epoch 2/100
3/3 [==============================] - 0s 665us/sample - loss: 38.1438
Epoch 3/100
3/3 [==============================] - 0s 665us/sample - loss: 30.3014
Epoch 4/100
3/3 [==============================] - 0s 665us/sample - loss: 36.1595
Epoch 5/100
3/3 [==============================] - 0s 667us/sample - loss: 31.3262
Epoch 6/100
3/3 [==============================] - 0s 997us/sample - loss: 28.7858
Epoch 7/100
3/3 [==============================] - 0s 997us/sample - loss: 30.3187
Epoch 8/100
3/3 [==============================] - 0s 997us/sample - loss: 31.4583
Epoch 9/100
3/3 [==============================] - 0s 997us/sample - loss: 30.5034
Epoch 10/100
3/3 [==============================] - 0s 665us/sample - loss: 28.6972
Epoch 11/100
3/3 [==============================] - 0s 664us/sample - loss: 28.3186
Epoch 12/100
3/3 [==============================] - 0s 333us/sampl

Epoch 99/100
3/3 [==============================] - 0s 680us/sample - loss: 27.8879
Epoch 100/100
3/3 [==============================] - 0s 665us/sample - loss: 27.8878


In [9]:
model.predict(x_train)

array([[ 0.       ,  2.244743 ,  0.       ,  4.3144503,  5.551099 ],
       [ 0.       ,  7.230582 ,  0.       ,  9.38292  , 10.519164 ],
       [ 0.       , 12.2174425,  0.       , 14.462728 , 15.491745 ]],
      dtype=float32)

In [10]:
model.evaluate(x_train,y_train)

3/1 [==========================================================================================] - 0s 25ms/sample - loss: 27.8879


27.887855529785156

### [2] Flatten Layer

In [13]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None, 28, 28, 10)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28*10) = (None,7840)

(1000, 28, 28, 10)
(1000, 7840)


In [14]:
# 3차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28).reshape(1000,28,28).astype(np.float32)
print(data.shape) # (None, 28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28) = (None,784)

(1000, 28, 28)
(1000, 784)


In [15]:
# 2차원 데이터는 그대로 2차원으로 FC Layer에 전달
data = np.arange(28*28).reshape(28,28).astype(np.float32)
print(data.shape) # (28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (28,28) 

(28, 28)
(28, 28)


### [3] Dropout Layer

In [16]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set to True automatically, and in other contexts, you can set 
# the kwarg explicitly to True when calling the layer.

# (This is in contrast to setting trainable=False for a Dropout layer.
# trainable does not affect the layer's behavior, as Dropout does not have any 
# variables/weights that can be frozen during training.)

In [30]:
# 신버전 keras dropout

tf.random.set_seed(0)
data = np.arange(10).reshape(5,2).astype(np.float32)
print(data)

layer = tf.keras.layers.Dropout(0.3,input_shape=(2,))

outputs = layer(data,training=True)
# model.fit()호출 시는  학습 모드로 training=True가 되어 dropuout 적용
# model.evaluate() 호출 시는 예측 모드로 False가 되어 dropuout이 수행되지 않음
print(outputs) # 데이터의 30%는 0으로 나머지 데이터는  1/(1-0.3)으로 곱하여 scaled up된다
print(data*1/(1 - 0.3))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]


In [31]:
# 구버전 dropout : 사용이 번거로움
tf.random.set_seed(0)

data = np.arange(10).reshape(5,2).astype(np.float32)

def layer1(X,dr_rate):
    return tf.nn.dropout(X,rate=dr_rate)

layer1(data,dr_rate=0.3)    

<tf.Tensor: id=16214, shape=(5, 2), dtype=float32, numpy=
array([[ 0.       ,  0.       ],
       [ 2.857143 ,  4.285714 ],
       [ 5.714286 ,  7.1428576],
       [ 8.571428 , 10.       ],
       [11.428572 ,  0.       ]], dtype=float32)>

In [1]:
# VGGNet (VGG-19) 스타일의 MNIST 분류 CNN 모델 
#--------------------------------------------
# ( Conv2D * 2개  --> MaxPool2D ) * 2회 : 4층
# ( Conv2D * 4개  --> MaxPool2D ) * 3회 : 12층
# Dense * 3개                           : 3층
#--------------------------------------------
#                                     총 19층
#--------------------------------------------
# 각 네트워크마다 필터의 수를 2배로 증가 시킨다 : 32-->64-->128-->256-->512

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(input_shape=(28,28,1), kernel_size=(3,3), filters=32, padding='same', activation='relu'),
    tf.keras.layers.Conv2D(kernel_size=(3,3), filters=64, padding='same', activation='relu'),
    tf.keras.layers.MaxPool2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Conv2D(kernel_size=(3,3), filters=128, padding='same', activation='relu'),
    tf.keras.layers.Conv2D(kernel_size=(3,3), filters=256, padding='valid', activation='relu'),
    tf.keras.layers.MaxPool2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=512, activation='relu'),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Dense(units=10, activation='softmax')
])




NameError: name 'tf' is not defined

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(), 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

model.summary()
